//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.11 at 07:23:45 PM EET 
//


package com.company.task205.city;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.company.task205.city package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.company.task205.city
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CityData }
     */
    public CityData createCityData() {
        return new CityData();
    }

    /**
     * Create an instance of {@link CityData.DistrictsData }
     */
    public CityData.DistrictsData createCityDataDistrictsData() {
        return new CityData.DistrictsData();
    }

    /**
     * Create an instance of {@link CityData.DistrictsData.DistrictData }
     */
    public CityData.DistrictsData.DistrictData createCityDataDistrictsDataDistrictData() {
        return new CityData.DistrictsData.DistrictData();
    }

    /**
     * Create an instance of {@link CityData.DistrictsData.DistrictData.FirstNameData }
     */
    public CityData.DistrictsData.DistrictData.FirstNameData createCityDataDistrictsDataDistrictDataFirstNameData() {
        return new CityData.DistrictsData.DistrictData.FirstNameData();
    }

}
